import javax.swing.*;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.net.*;
import java.util.*;
import javax.swing.table.DefaultTableModel;


public class customerGui extends javax.swing.JFrame {

    private Socket server;
    private ObjectOutputStream out;
    private ObjectInputStream in;
    private String response;
    public customerGui() {
        initComponents();
        
      
        
    }
    public void displayCustomerTable()
    {
        try
        {
            DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
            model.setRowCount(0);
            int count = 0;
            int no = 0;
            String name = "",surname = "",address = "";
            boolean confirm = false;
            server = new Socket("127.0.0.1", 12345);
            
            out = new ObjectOutputStream(server.getOutputStream());
            out.flush();
            in = new ObjectInputStream(server.getInputStream());
            sendData("Display Customers");
            do
            {
                receiveData();
                if(!response.equalsIgnoreCase("Customer Display successful"))
                {
                    switch(count)
                    {
                        case 0:
                            no = Integer.parseInt(response);
                            count++;
                            break;
                        case 1:
                            name = response;
                            count++;
                            break;
                        case 2:
                            surname = response;
                            count++;
                            break;
                        case 3:
                            address = response;
                            count++;
                            break;
                        case 4:
                            confirm = Boolean.parseBoolean(response);
                            model.addRow(new Object[]{no,name,surname,address,confirm});
                            count = 0;
                            break;
                    }
                }
            }while(!response.equalsIgnoreCase("Customer Display successful"));
            
            sendData("Stop");
            server.close();
            in.close();
            out.close();
        }
        catch (IOException ioe)
        {
            System.out.println("IOException: " + ioe.getMessage());
        }
    }

    public void sendData(String msg)
    {
        // The connection has been established - now send/receive.
        
        try
        {
            out.writeObject(msg);
            out.flush();
        }
        catch (IOException ioe)
        {
            System.out.println("IO Exception: " + ioe.getMessage());
        }
    }
    public void receiveData()
    {
        try
        {
            response = (String)in.readObject();
            System.out.println("SERVER said>> " + response);
          
        }
        catch (IOException ioe)
        {
            System.out.println("IO Exception: " + ioe.getMessage());
        }
        catch (ClassNotFoundException cnfe)
        {
            System.out.println("Class not found: " + cnfe.getMessage());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButtonAdd = new javax.swing.JButton();
        jButtonEdit = new javax.swing.JButton();
        jButtonDelete = new javax.swing.JButton();
        jButtonExit = new javax.swing.JButton();
        jButtonRefresh = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(795, 615));
        setResizable(false);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowClosed(java.awt.event.WindowEvent evt) {
                Closing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                Open(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Algerian", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 204));
        jLabel1.setText("Customer");
        jLabel1.setName("LabelCustHeading"); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, -1, -1));

        jTable1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "custNumber", "firstName", "lastName", "address", "canRent"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(jTable1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 730, 210));

        jButtonAdd.setBackground(new java.awt.Color(0, 102, 255));
        jButtonAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/addCust.png"))); // NOI18N
        jButtonAdd.setToolTipText("Add Customer");
        jButtonAdd.setName(""); // NOI18N
        jButtonAdd.setOpaque(false);
        jButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, 120, 120));

        jButtonEdit.setBackground(new java.awt.Color(0, 102, 255));
        jButtonEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/editCust.png"))); // NOI18N
        jButtonEdit.setToolTipText("Edit Customer");
        jButtonEdit.setName(""); // NOI18N
        jButtonEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 480, 120, 120));

        jButtonDelete.setBackground(new java.awt.Color(0, 102, 255));
        jButtonDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/removeCust.png"))); // NOI18N
        jButtonDelete.setToolTipText("Delet Customer");
        jButtonDelete.setName(""); // NOI18N
        jButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 480, 120, 120));

        jButtonExit.setBackground(new java.awt.Color(0, 102, 255));
        jButtonExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cancelCust.png"))); // NOI18N
        jButtonExit.setToolTipText("Cancel");
        jButtonExit.setName(""); // NOI18N
        jButtonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 470, 120, 120));

        jButtonRefresh.setBackground(new java.awt.Color(0, 102, 255));
        jButtonRefresh.setText("Refresh");
        jButtonRefresh.setToolTipText("Cancel");
        jButtonRefresh.setName(""); // NOI18N
        jButtonRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRefreshActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonRefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 320, 120, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/custFrontCover.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 620));

        setSize(new java.awt.Dimension(808, 642));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExitActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButtonExitActionPerformed

    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddActionPerformed
        // TODO add your handling code here:
        customerEditGui form = new customerEditGui();
        form.setVisible(true);
         
    }//GEN-LAST:event_jButtonAddActionPerformed

    private void jButtonEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditActionPerformed
        // TODO add your handling code here:
        
        if(jTable1.getSelectedRow() == -1)
        {
            if(jTable1.getRowCount() == 0)
                JOptionPane.showMessageDialog(rootPane, "Table is empty");
            else
                JOptionPane.showMessageDialog(rootPane, "You must Select a product");
        }
        else 
        {
            int no = Integer.parseInt(jTable1.getValueAt(jTable1.getSelectedRow(),0).toString());
            String name = jTable1.getValueAt(jTable1.getSelectedRow(),1).toString();
            String surname = jTable1.getValueAt(jTable1.getSelectedRow(),2).toString();
            String address = jTable1.getValueAt(jTable1.getSelectedRow(),3).toString();
            boolean confirm = Boolean.parseBoolean(jTable1.getValueAt(jTable1.getSelectedRow(),4).toString());
            customerEditGui form = new customerEditGui(no,name,surname,address,confirm);
            form.setVisible(true);
        }
    }//GEN-LAST:event_jButtonEditActionPerformed

    private void Closing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_Closing
        // TODO add your handling code here:
        
    }//GEN-LAST:event_Closing

    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteActionPerformed
        // TODO add your handling code here:
        
        if(jTable1.getSelectedRow() == -1)
        {
            if(jTable1.getRowCount() == 0)
                JOptionPane.showMessageDialog(rootPane, "Table is empty");
            else
                JOptionPane.showMessageDialog(rootPane, "You must Select a product");
        }
        else 
        {
            try
            {
                // STEP 1 b
                // Create socket TO SERVER
                server = new Socket("127.0.0.1", 12345);

                out = new ObjectOutputStream(server.getOutputStream());
                out.flush();
                in = new ObjectInputStream(server.getInputStream());
                sendData("Delete Customer");
                sendData(jTable1.getValueAt(jTable1.getSelectedRow(),0).toString());
                receiveData();
                sendData("Stop");
                server.close();
                in.close();
                out.close();
            }
            catch (IOException ioe)
            {
                System.out.println("IOException: " + ioe.getMessage());
            }
        }
        
    }//GEN-LAST:event_jButtonDeleteActionPerformed

    private void Open(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_Open
        // TODO add your handling code here:
        displayCustomerTable();
    }//GEN-LAST:event_Open

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        //displayCustomerTable();
    }//GEN-LAST:event_formWindowActivated

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        // TODO add your handling code here:
        //displayCustomerTable();
    }//GEN-LAST:event_formWindowGainedFocus

    private void jButtonRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRefreshActionPerformed
        // TODO add your handling code here:
        displayCustomerTable();
    }//GEN-LAST:event_jButtonRefreshActionPerformed

    /**
     * @param args the command line arguments
     */
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonEdit;
    private javax.swing.JButton jButtonExit;
    private javax.swing.JButton jButtonRefresh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
