
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.net.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class vehicleGui extends javax.swing.JFrame {

    private Socket server;
    private ObjectOutputStream out;
    private ObjectInputStream in;
    private String response;
    private int vehicleNumber;
    private String vehicleMake;
    private String vehicleCategory;
    private int category;
    private float vehicleRentalPrice;
    private boolean vehicleAvailability;
    /**
     * Creates new form vehicleGui
     */
    public vehicleGui() {
        initComponents();
    }
    
    public void displayVehicleTable()
    {
        try
        {
            DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
            model.setRowCount(0);
            int count = 0;
            int no = 0;
            String make = "",category = "";
            boolean confirm = false;
            float price = 0;
            server = new Socket("127.0.0.1", 12345);
            
            out = new ObjectOutputStream(server.getOutputStream());
            out.flush();
            in = new ObjectInputStream(server.getInputStream());
            sendData("Display Vehicle");
            System.out.println("Vehicle send");
            do
            {
                System.out.println("Vehicle send");
                receiveData();
                if(!response.equalsIgnoreCase("Vehicle Display successful"))
                {
                    switch(count)
                    {
                        case 0:
                            no = Integer.parseInt(response);
                            count++;
                            break;
                        case 1:
                            make = response;
                            count++;
                            break;
                        case 2:
                            category = response;
                            count++;
                            break;
                        case 3:
                            price = Float.parseFloat(response);
                            count++;
                            break;
                        case 4:
                            confirm = Boolean.parseBoolean(response);
                            model.addRow(new Object[]{no,make,category,price,confirm});
                            count = 0;
                            break;
                    }
                }
            }while(!response.equalsIgnoreCase("Vehicle Display successful"));
            
            sendData("Stop");
            server.close();
            in.close();
            out.close();
        }
        catch (IOException ioe)
        {
            System.out.println("IOException: " + ioe.getMessage());
        }
    }
     public void sendData(String msg)
    {
        // The connection has been established - now send/receive.
        
        try
        {
            out.writeObject(msg);
            out.flush();
        }
        catch (IOException ioe)
        {
            System.out.println("IO Exception: " + ioe.getMessage());
        }
    }
    public void receiveData()
    {
        try
        {
            response = (String)in.readObject();
            System.out.println("SERVER said>> " + response);
          
        }
        catch (IOException ioe)
        {
            System.out.println("IO Exception: " + ioe.getMessage());
        }
        catch (ClassNotFoundException cnfe)
        {
            System.out.println("Class not found: " + cnfe.getMessage());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButtonAdd = new javax.swing.JButton();
        jButtonEdit = new javax.swing.JButton();
        jButtonDelete = new javax.swing.JButton();
        jButtonExit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButtonRefresh = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(795, 615));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                Open(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "vehNumber", "make", "category", "rentalPrice", "availableForRent"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 775, 210));

        jButtonAdd.setBackground(new java.awt.Color(255, 204, 0));
        jButtonAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/addIconVeh.png"))); // NOI18N
        jButtonAdd.setToolTipText("Add Vehicle");
        jButtonAdd.setName(""); // NOI18N
        jButtonAdd.setOpaque(false);
        jButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 480, 120, 120));

        jButtonEdit.setBackground(new java.awt.Color(255, 204, 0));
        jButtonEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/editIconVeh.png"))); // NOI18N
        jButtonEdit.setToolTipText("Edit Vehicle");
        jButtonEdit.setName(""); // NOI18N
        jButtonEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 480, 110, 120));

        jButtonDelete.setBackground(new java.awt.Color(255, 204, 0));
        jButtonDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/remIconVeh.png"))); // NOI18N
        jButtonDelete.setToolTipText("Delete Vehicle");
        jButtonDelete.setName(""); // NOI18N
        jButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 480, 120, 120));

        jButtonExit.setBackground(new java.awt.Color(255, 204, 0));
        jButtonExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cancelIconVeh.png"))); // NOI18N
        jButtonExit.setToolTipText("Cancel ");
        jButtonExit.setName(""); // NOI18N
        jButtonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 480, 120, 120));

        jLabel1.setFont(new java.awt.Font("Algerian", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 204, 0));
        jLabel1.setText("Vehicle");
        jLabel1.setName("LabelVehHeading"); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, -1, -1));

        jButtonRefresh.setText("Refresh");
        jButtonRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRefreshActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonRefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 320, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vehicleFrontCover_1.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 620));

        setSize(new java.awt.Dimension(801, 642));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddActionPerformed
        // TODO add your handling code here:
        vehicleEditGui form = new vehicleEditGui();
        form.setVisible(true);
    }//GEN-LAST:event_jButtonAddActionPerformed

    private void jButtonEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditActionPerformed
        // TODO add your handling code here:
        if(jTable1.getSelectedRow() == -1)
        {
            if(jTable1.getRowCount() == 0)
                JOptionPane.showMessageDialog(rootPane, "Table is empty");
            else
                JOptionPane.showMessageDialog(rootPane, "You must Select a product");
        }
        else 
        {
            int no = Integer.parseInt(jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString());
            String make = jTable1.getValueAt(jTable1.getSelectedRow(), 1).toString();
            String category = jTable1.getValueAt(jTable1.getSelectedRow(), 2).toString();
            boolean confirm = Boolean.parseBoolean(jTable1.getValueAt(jTable1.getSelectedRow(), 4).toString());
            vehicleEditGui form = new vehicleEditGui(no,make,category,confirm);
            form.setVisible(true);
        }
    }//GEN-LAST:event_jButtonEditActionPerformed

    private void jButtonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExitActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButtonExitActionPerformed

    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteActionPerformed
        // TODO add your handling code here:
        try
	{
            // STEP 1 b
            // Create socket TO SERVER
            server = new Socket("127.0.0.1", 12345);
            
            out = new ObjectOutputStream(server.getOutputStream());
            out.flush();
            in = new ObjectInputStream(server.getInputStream());
            sendData("Delete Vehicle");
            sendData("Vehicle data to delete");
            receiveData();
            sendData("Stop");
            server.close();
            in.close();
            out.close();
        }
        catch (IOException ioe)
        {
            System.out.println("IOException: " + ioe.getMessage());
        }
    }//GEN-LAST:event_jButtonDeleteActionPerformed

    private void Open(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_Open
        // TODO add your handling code here:
        displayVehicleTable();
    }//GEN-LAST:event_Open

    private void jButtonRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRefreshActionPerformed
        // TODO add your handling code here:
        displayVehicleTable();
    }//GEN-LAST:event_jButtonRefreshActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonEdit;
    private javax.swing.JButton jButtonExit;
    private javax.swing.JButton jButtonRefresh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
